### ISSUE TITLE
Not working: https://amber1.ddns.net/webapi/profile/purchases/

### ISSUE THREAD

**Issue by harrysy088** [ambertime/amberchain#10]
walletaddress: 1DUppkAj2ErRQB3kQN8vGTk59z4ebx7nMb

result: 
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

**Comment by maroon-olivia** [comment]
Hi,

Server response is 404 because of the trailing forward slash (`/`). 
Please omit the `/` (i.e. `https://amber1.ddns.net/webapi/profile/purchases`)

Thanks!
