### ISSUE TITLE
Not working: /webapi/services/claim

### ISSUE THREAD

**Issue by harrysy088** [ambertime/amberchain#11]
Trying to claim a product using confirmation code but failed (p35 of documentation):
 url: https://amber1.ddns.net/webapi/services/claim

Result:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>

**Comment by harrysy088** [comment]
The fields are:
address:1DUppkAj2ErRQB3kQN8vGTk59z4ebx7nMb
roottxid:f8654d40055200fd0fbaafa40b7f0114f9369ef800efda8be63fab00021d3bef
newstatus:claim
confirmationcode:193f7dc699e9b31cd0ea6b911a57c862ee607390922dcd23274b21fcf2edec416a8542f0c7ea95a5c11f99416df1b554f02c23bb3160683afb4a5507182e402b

**Comment by maroon-olivia** [comment]
Hi,

The URL endpoint we have indicated in the documentation is incorrect. Please use `https://amber1.ddns.net/webapi/services/claimservice`. 
We'll update the document with this.

Thanks!
