### ISSUE TITLE
节点连接测试链 api调用问题

### ISSUE THREAD

**Issue by ItMrj** [ambertime/amberchain#15]
按照 readme 中的节点搭建方法搭建了本地节点，但是在调用 help 方法时，节点会与测试链断开连接， getInfo createKeypairs 方法可以正常使用，调用 getbalance {address} 时，提示不能使用 scaleable 钱包获取账户信息。按照给的提示方法设置 ..version=1 -recan 不能启动节点。

**Comment by maroon-olivia** [comment]
Issue here is the same as the recent comment in issue #13. 

Let's have the discussion there. Thanks!
